app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout
    
excel_product_stream:
    path:      /product/excel
    defaults:  { _controller: AppBundle:Fake:stream }

pdf_product_stream:
    path:      /product/pdf
    defaults:  { _controller: AppBundle:Fake:streamPDF }

fake_route_store:
    path:      /fake/store
    defaults:  { _controller: AppBundle:Fake:store }

fake_route_read:
    path:      /fake/read
    defaults:  { _controller: AppBundle:Fake:readAndSave }

fake_route_insert:
    path:      /fake/insert/{file}
    defaults:  { _controller: AppBundle:Fake:insert }
